package UI;


import DB_Classes.Select;
import DB_Classes.employeeDB;

import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author yasmi
 */
public class ForgotPassword extends javax.swing.JFrame {
    String email;

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfSecurityQuestion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfAnswer = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 221, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton3.setBackground(new java.awt.Color(144, 52, 43));
        closeButton3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        closeButton3.setForeground(new java.awt.Color(255, 255, 255));
        closeButton3.setText("Exit");
        closeButton3.setFocusPainted(false);
        closeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 60, 20));

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot Password ?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 240, 51));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 133, 20));

        tfEmail.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tfEmail.setToolTipText("Enter an existing email");
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        jPanel1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 313, -1));

        searchButton.setBackground(new java.awt.Color(102, 0, 0));
        searchButton.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tfSecurityQuestion.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(tfSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 313, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("Security Question");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, 30));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("Answer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 133, 20));

        tfAnswer.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tfAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnswerActionPerformed(evt);
            }
        });
        jPanel1.add(tfAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 313, -1));

        pfPassword.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(pfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 310, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setText("New Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 133, 20));

        saveButton.setBackground(new java.awt.Color(102, 0, 0));
        saveButton.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));

        signupButton.setBackground(new java.awt.Color(102, 0, 0));
        signupButton.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("Signup");
        jPanel1.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        loginButton.setBackground(new java.awt.Color(102, 0, 0));
        loginButton.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // initialize a boolean variable to check if the email field is empty or not
    boolean check=false;
    // retrieve the email from the email field in the UI
    email=tfEmail.getText();
    // check if the email field is empty
    if(email.equals("")){
        check=true;
        JOptionPane.showMessageDialog(null, "Email Field is Required");
    }
    // if the email field is not empty, check if it is a valid email address
    else if (!isValidEmail(email)){
        // if it is not a valid email address, display an error message and clear the email field
        JOptionPane.showMessageDialog(null, "Invalid email address", "Error", JOptionPane.ERROR_MESSAGE);
        tfEmail.setText("");
    }
    else{
        // if the email address is valid, retrieve the corresponding record from the database
        ResultSet rs=Select.getData("select * from employees where emailEmp = '"+email+"'");
        try{
            if (rs.next())
            {
                // if a record is found, set the check variable to true
                check=true;
                // set the security question field in the UI to the corresponding security question from the record
                tfSecurityQuestion.setEditable(false);
                tfEmail.setEditable(false);
                tfSecurityQuestion.setText(rs.getString(8));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    // if the check variable is false, it means that the email does not exist in the database
    if (!check){
        JOptionPane.showMessageDialog(null, "This Email Does Not Exist");
    }
    }//GEN-LAST:event_searchButtonActionPerformed
public static boolean isValidEmail(String email) {
    if (email == null || email.isEmpty()) {
        return false;
    }
    int atPos = email.indexOf('@');
    if (atPos < 1 || atPos != email.lastIndexOf('@')) {
        return false;
    }
    String domain = email.substring(atPos + 1);
    if (domain.isEmpty() || domain.indexOf('.') < 1 || domain.lastIndexOf('.') == domain.length() - 1) {
        return false;
    }
    return true;
}
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnswerActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
         boolean check=false; // initialize a boolean variable as false
        String SecurityQuestion=tfSecurityQuestion.getText(); // get the security question from the text field
        String answer=tfAnswer.getText(); // get the answer to the security question from the text field
        String newpassword=pfPassword.getText(); // get the new password from the password field

        if(answer.equals("")||newpassword.equals("")){ // check if either the answer or the new password fields are empty
            check=true; // set the check variable to true if either field is empty
            JOptionPane.showMessageDialog(null, "All Fields are required"); // show a message dialog indicating that all fields are required
        }
        else{ // if both fields are filled
            ResultSet rs =Select.getData("select * from employees where emailEmp = '"+email+"' and SecurityQuestion='"+SecurityQuestion+"' and answer= '"+answer+"'");
            // execute a SQL query to check if the security question and answer provided are correct for the given email
            try {
                if(rs.next()){ // if the query returns a row, the answer to the security question is correct
                    check=true; // set the check variable to true
                    employeeDB.updateEmp("update employees set password= '"+newpassword+"' where emailEmp ='"+email+"'" , "Password Set Successfully");
                    // execute a SQL query to update the password for the given email
                    dispose(); // close the current window
                    new Login().setVisible(true); // open the login window
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e); // show an error message if an exception occurs
            }
        }
        if(!check){ // if the check variable is still false, the answer to the security question is incorrect
            JOptionPane.showMessageDialog(null, "Incorrect Answer"); // show an error message indicating that the answer is incorrect
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        String email = tfEmail.getText();
        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Invalid email address", "Error", JOptionPane.ERROR_MESSAGE);
            tfEmail.setText("");
        }
    }//GEN-LAST:event_tfEmailFocusLost

    private void closeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton3ActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do You Really Want To Close the Application ? ", "Select an option", JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField tfAnswer;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfSecurityQuestion;
    // End of variables declaration//GEN-END:variables
}
