package UI;


import Classes.Employee;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

//import project.InsertUpdateDelete;
import DB_Classes.employeeDB;


/**
 *
 * @author yasmi
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    Employee emp = new Employee();
    employeeDB db = new employeeDB();
    ResultSet result = null;
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_CIN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_FNEmp = new javax.swing.JTextField();
        tf_LNEmp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_phoneEmp = new javax.swing.JTextField();
        tf_emailEmp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sec_quest = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tf_answer = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        forgotpasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 221, 204));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeButton.setBackground(new java.awt.Color(144, 52, 43));
        closeButton.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Exit");
        closeButton.setToolTipText("");
        closeButton.setFocusPainted(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 10, 60, 20));

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setText("Signup");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel7.setText("N° CIN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 150, 22));

        tf_CIN.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tf_CIN.setToolTipText("Digits Only");
        tf_CIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_CINActionPerformed(evt);
            }
        });
        tf_CIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_CINKeyTyped(evt);
            }
        });
        jPanel1.add(tf_CIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 332, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel8.setText("First Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 122, 22));

        tf_FNEmp.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(tf_FNEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 332, -1));

        tf_LNEmp.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tf_LNEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_LNEmpActionPerformed(evt);
            }
        });
        jPanel1.add(tf_LNEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 332, -1));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 122, 20));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel10.setText("Telephone");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 122, 20));

        tf_phoneEmp.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tf_phoneEmp.setToolTipText("Digits Only");
        tf_phoneEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_phoneEmpActionPerformed(evt);
            }
        });
        tf_phoneEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_phoneEmpKeyTyped(evt);
            }
        });
        jPanel1.add(tf_phoneEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 332, -1));

        tf_emailEmp.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tf_emailEmp.setToolTipText("Enter a valid email");
        tf_emailEmp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_emailEmpFocusLost(evt);
            }
        });
        tf_emailEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailEmpActionPerformed(evt);
            }
        });
        jPanel1.add(tf_emailEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 332, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 146, 20));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setText("Userame");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 152, 20));

        tf_username.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jPanel1.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 332, -1));
        tf_username.getAccessibleContext().setAccessibleName("");
        tf_username.getAccessibleContext().setAccessibleDescription("");

        pf_password.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        pf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 332, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 152, 20));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setText("Security Question");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 152, 20));

        sec_quest.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        sec_quest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is the name of your first pet?", "What was your first car?", "What elementary school did you attend?", "What is the name of the town where you were born?" }));
        sec_quest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec_questActionPerformed(evt);
            }
        });
        jPanel1.add(sec_quest, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 332, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel6.setText("Answer");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 148, 20));

        tf_answer.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        tf_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_answerActionPerformed(evt);
            }
        });
        jPanel1.add(tf_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 332, -1));

        btn_signup.setBackground(new java.awt.Color(102, 0, 0));
        btn_signup.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        btn_signup.setForeground(new java.awt.Color(255, 255, 255));
        btn_signup.setText("Signup");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        jPanel1.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        loginButton.setBackground(new java.awt.Color(102, 0, 0));
        loginButton.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 560, -1, -1));

        forgotpasswordButton.setBackground(new java.awt.Color(102, 0, 0));
        forgotpasswordButton.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        forgotpasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        forgotpasswordButton.setText("Forgot Password ?");
        forgotpasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpasswordButtonActionPerformed(evt);
            }
        });
        jPanel1.add(forgotpasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forgotpasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpasswordButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_forgotpasswordButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do You Really Want To Close the Application ? ", "Select an option", JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
    // Check if email is valid and all fields are filled
       if((!isValidEmail(tf_emailEmp.getText())) || isAnyRequiredFieldEmpty(tf_emailEmp.getText())) {
           JOptionPane.showMessageDialog(null, "Every Field is Required");
           emp = null; // Set emp to null to indicate that the employee creation failed
       } else {
           // Create a new Employee object and insert it into the database
           ObjectCreation();
           db.insertEmployee(emp);
           emptyField();
       }

    }//GEN-LAST:event_btn_signupActionPerformed
 private boolean isAnyRequiredFieldEmpty(String text) {
        return ((tf_CIN.getText()).equals("")||tf_FNEmp.getText().equals("")||tf_LNEmp.getText().equals("")||(tf_phoneEmp.getText()).equals("")||tf_emailEmp.getText().equals("")||tf_username.getText().equals("")||pf_password.getText().equals("")||tf_answer.getText().equals(""));
    }
    private void tf_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_answerActionPerformed

    private void sec_questActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec_questActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sec_questActionPerformed

    private void pf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_passwordActionPerformed

    private void tf_emailEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailEmpActionPerformed

    private void tf_emailEmpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_emailEmpFocusLost
        // TODO add your handling code here:
        String email = tf_emailEmp.getText();
        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Invalid email address", "Error", JOptionPane.ERROR_MESSAGE);
            tf_emailEmp.setText("");
        }
    }//GEN-LAST:event_tf_emailEmpFocusLost

    private void tf_phoneEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_phoneEmpKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tf_phoneEmpKeyTyped

    private void tf_phoneEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_phoneEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_phoneEmpActionPerformed

    private void tf_LNEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_LNEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LNEmpActionPerformed

    private void tf_CINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_CINKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tf_CINKeyTyped

    private void tf_CINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_CINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_CINActionPerformed
        /*
        This method creates an object of the Employee class and sets its properties based on the data entered in the text fields of the Employee Panel.
        If any exception occurs, the method displays an error message.
        */
        private void ObjectCreation(){
        // create a new Employee object
        emp = new Employee();
        try{
        // set the properties of the Employee object based on the data entered in the text fields of the Employee Panel
        emp.setCin(Integer.parseInt(tf_CIN.getText()));
        emp.setFN(tf_FNEmp.getText());
        emp.setLN(tf_LNEmp.getText());
        emp.setEmail(tf_emailEmp.getText());
        emp.setPhone(Integer.parseInt(tf_phoneEmp.getText()));
        emp.setUsername(tf_username.getText());
        emp.setPassword(pf_password.getText());
        emp.setSecurityquestion((String)sec_quest.getSelectedItem());
        emp.setAnswer(tf_answer.getText());
        }
        // catch any exception that occurs and display an error message
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
        }
        }
    public void emptyField(){
        emp = new Employee();
        
        tf_CIN.setText("");
        tf_FNEmp.setText("");
        tf_LNEmp.setText("");
        tf_phoneEmp.setText("");
        tf_emailEmp.setText("");
        tf_username.setText("");
        pf_password.setText("");
        tf_answer.setText("");
        
        
        
    }
public static boolean isValidEmail(String email) {
    if (email == null || email.isEmpty()) {
        return false;
    }
    int atPos = email.indexOf('@');
    if (atPos < 1 || atPos != email.lastIndexOf('@')) {
        return false;
    }
    String domain = email.substring(atPos + 1);
    if (domain.isEmpty() || domain.indexOf('.') < 1 || domain.lastIndexOf('.') == domain.length() - 1) {
        return false;
    }
    return true;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton forgotpasswordButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JComboBox<String> sec_quest;
    private javax.swing.JTextField tf_CIN;
    private javax.swing.JTextField tf_FNEmp;
    private javax.swing.JTextField tf_LNEmp;
    private javax.swing.JTextField tf_answer;
    private javax.swing.JTextField tf_emailEmp;
    private javax.swing.JTextField tf_phoneEmp;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
